### ISSUE TITLE
Anti Clockwise support

### ISSUE THREAD

**Issue by alexanderkorus** [gregttn/GTProgressBar#10]
Hey,

is it possible to support anti clockwise progress which animate from right to left (see the left progress bar below)?

<img width="363" alt="anticlockwise" src="https://user-images.githubusercontent.com/14931519/31139519-1d887fe0-a872-11e7-82f3-75fb37a9dc69.png">

Thanks in advance!
Alex

**Comment by alexanderkorus** [comment]
Hello again,

I solve my problem by adding the anti clockwise support by myself. And have make a new Pull Request
#11

**Comment by gregttn** [comment]
Thanks!
