### ISSUE TITLE
Carthage Issue

### ISSUE THREAD

**Issue by ChandraGillellamudi** [gregttn/GTProgressBar#12]
<unknown>:0: error: filename "UILabelExtensions.swift" used twice:

I am getting  above error while checking out from Carthage

Carthage version: 0.24.0

**Comment by gregttn** [comment]
Hi,

Thanks for flagging. Carthage was pulling in version 0.2.0 which does not support Swift 4. I released the new version 0.2.1 with support for Swift 4 which gets rid of that problem.

Greg

**Comment by riki-dexter** [comment]
Hi @gregttn,
I'm getting this same issue. I tried version 0.2.1 and 0.2.2 but Carthage fails with this log:
```
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/ricdes/ENDev/iOS/ENFusion/Carthage/Checkouts/GTProgressBar/GTProgressBar.xcodeproj -scheme GTProgressBar -configuration Release -derivedDataPath /Users/ricdes/Library/Caches/org.carthage.CarthageKit/DerivedData/9.1_9B55/GTProgressBar/0.2.2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath ./ SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/ricdes/ENDev/iOS/ENFusion/Carthage/Checkouts/GTProgressBar)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/dz/7_mm3_jd5yl6tq8v9l2dklz80000gn/T/carthage-xcodebuild.xjKObA.log

```

**Comment by gregttn** [comment]
Hi @riki-dexter 
Yes you are right there is a problem with the Carthage build. I forgot to amend the Xcode project for Carthage before pushing the new version. I will fix it shortly.

Thanks for flagging!

**Comment by gregttn** [comment]
@riki-dexter it should work now.

**Comment by riki-dexter** [comment]
Yeah, it works!
Thank you.
