### ISSUE TITLE
Swift 4 Incorrect argument label in call (have 'withAttributes:', expected 'attributes:')

### ISSUE THREAD

**Issue by loopingGIT** [gregttn/GTProgressBar#14]
I migrated my project to swift 4, updated the pods and now I am getting that error on _UILabelExtension.swift_ file. When updating the pod list that I am using Using GTProgressBar (0.2.1)

```
import Foundation

internal extension UILabel {
    internal static func sizeFor(content: NSString, font: UIFont) -> CGSize {
        let text: NSString = content
        //here is the error
        let textSize = text.size(withAttributes: [NSAttributedStringKey.font : font]) 
        // it should be?
        let textSize = text.size(attributes: [NSAttributedStringKey.font : font])
        
        return CGSize(width: ceil(textSize.width), height: ceil(textSize.height))
    }
}
```

**Comment by gregttn** [comment]
Hi,

Are you sure you updated the project and pods? According to the documentation the code that is showing an error is correct. The version that you point to is the old way.

[https://developer.apple.com/documentation/foundation/nsstring/1531844-size](https://developer.apple.com/documentation/foundation/nsstring/1531844-size)

Greg

**Comment by loopingGIT** [comment]
Greg, thanks for the quick response. Yes I did. What I did to solve the problems was first migrate the  project to Swift 4 and then update all the pods again. Now I am not having this issue with 
`let textSize = text.size(withAttributes: [NSAttributedStringKey.font : font])`.

**Comment by gregttn** [comment]
Ok, glad you got it working.

Greg
