### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by riki-dexter** [gregttn/GTProgressBar#15]
Hi @gregttn,
can corner radius be set to be fully squared? 
Despite `progressBar.cornerRadius = 0.0` progress bar has a small corner radius.
I achieve my aim by setting  `progressBar.cornerRadius = -2.0` but I don't know if it is the right way.
Thank you.

**Comment by gregttn** [comment]
Yes, the default cornerRadius is applied when 0 is specified. The default radius depends on the height/width of the view so it will not always be -2.

I think this is confusing and will treat it as  bug. 
Thanks for flagging.

**Comment by gregttn** [comment]
This was addressed in 0.2.4 release. You can now specify corner type.
