### ISSUE TITLE
Bar & Background Colour Disappear When Embedded in UITableViewCell & Selected

### ISSUE THREAD

**Issue by LoicVerrall** [gregttn/GTProgressBar#18]
Hi, when I embed a `GTProgressBar` in a `UITableViewCell` and select that cell, the bar and background of the progress bar disappear (see photos attached). Is this a known issue?

<img width="547" alt="screen shot 2018-01-20 at 11 08 30" src="https://user-images.githubusercontent.com/17081120/35182742-4ec91230-fdd2-11e7-9422-0bf676bbfa59.png"><img width="547" alt="screen shot 2018-01-20 at 11 08 38" src="https://user-images.githubusercontent.com/17081120/35182743-4ee2d7ec-fdd2-11e7-951d-86c8949ce4f8.png">

**Comment by gregttn** [comment]
Hi,

No this was not reported before. From the screenshots it looks like the bar disappears on click, is that correct?

Greg

**Comment by LoicVerrall** [comment]
Yes, that’s right – as the cell becomes selected when I press down on it.

**Comment by gregttn** [comment]
Ok thanks. I managed to reproduce it.

**Comment by gregttn** [comment]
This issue happens because UITableViewCell is adjusting the background colour of all it's subviews when it is selected. I have some ideas how to address this but will need some time to actually apply them.
One of the immediate options you have is to have the selection of the cell set to 'none'.

**Comment by gregttn** [comment]
I have pushed a change that fixes this issue. It will be deployed in the next version of the pod.
