### ISSUE TITLE
Corner Radius

### ISSUE THREAD

**Issue by tooolbox** [gregttn/GTProgressBar#21]
I want to have a bar that's perfectly square, with no rounded corners.

Currently you have the property `@IBInspectable cornerRadius: CGFloat` but if you set it to zero it does not affect the inner layers:

```swift
private func updateViewsLocation() {
    backgroundView.layer.cornerRadius = cornerRadiusFor(view: backgroundView)
    fillView.layer.cornerRadius = cornerRadiusFor(view: fillView)
    ...
}

private func cornerRadiusFor(view: UIView) -> CGFloat {
    if cornerRadius != 0.0 {
        return cornerRadius
    }
    
    switch orientation {
    case .horizontal:
        return view.frame.height / 2 * 0.7
    case .vertical:
        return view.frame.width / 2 * 0.7
    }
}
```

I was able to get the bar to be totally square by doing `cornerRadius = -0.1` but this seems like a hack.  I would open a pull request but I'm not sure how you want to handle this.  Have `innerCornerRadius`?  Have a setting to deactivate the default cornerRadius calculation?

**Comment by gregttn** [comment]
Hi,

Thanks for looking into this. I prefer flexibility, so ideally both of them should be configurable. If not set, the inner and outer corner radius should be calculated automatically. Currently I use 0 value to indicate that the corner radius should be automatically calculated. I don't think that this is the best way to handle that case, optionals would be better.

Greg

**Comment by Raviojha62** [comment]
you can set the cornerradius  -10. it will work

**Comment by gregttn** [comment]
I have just pushed out a new version of the pod (0.2.4) which allows you to specify whether you want square or rounded corners.
