### ISSUE TITLE
Requiered Code Signature missing

### ISSUE THREAD

**Issue by albertomota-codes** [gregttn/GTProgressBar#23]
Suddenly, in my projects, this error came on!  may be the pod has updated, and the new version break it. I use this pod in 5 projects and suddenly all of them shows this error. Or maybe is the Xcode 9.3

<img width="842" alt="screen shot 2018-05-03 at 6 57 02 pm" src="https://user-images.githubusercontent.com/21207111/39610274-1d113d66-4f04-11e8-9566-aa5b1b7176ad.png">

Happens even in  new projects, please try.

**Comment by gregttn** [comment]
Thanks for flagging this.
I have managed to reproduce the problem. My assumptions are that you use @IBDesignables in your project and that you integrated the framework using CocoaPods v.1.5.0. Is that correct?

It appears that this is an issue with support for @IBDesignables in the newest version of CocoaPods. It works absolutely fine in version 1.4.0. There is an open issue in [CocoaPods to fix this.](https://github.com/CocoaPods/CocoaPods/issues/7606)

In the meantime I suggest to downgrade to version 1.4.0 of CocoaPods.

**Comment by albertomota-codes** [comment]
yes, the problem is using GTProgressBar in de xib as @IBDesignable!
Thanks a lot for the help!

**Comment by AresProductions** [comment]
If someone wants to use CocoaPods 1.5 there's [this solution which worked for me.](https://stackoverflow.com/a/50333958/6299567)

**Comment by gregttn** [comment]
The solution above seems to work. Thanks @AresProductions

**Comment by gregttn** [comment]
The newest Cocoapods release solves this issue.
