### ISSUE TITLE
How to Clear the Background Color 

### ISSUE THREAD

**Issue by zeshanmusawar** [gregttn/GTProgressBar#32]
I Want to Clear the Background Color . When i Add its Show the Wight color. How to Solve this Issue .
Thanks

**Comment by sungeunDev** [comment]
Did you fix it? I have the same problem

**Comment by gregttn** [comment]
Hi,

I assume you want to make the white part of the bar transparent?

<img width="334" alt="screenshot 2019-02-22 at 08 47 47" src="https://user-images.githubusercontent.com/1731472/53230456-9da31280-367e-11e9-9c1f-528f1e0ee5da.png">

In that case setting clear color will not work. Setting any color with opacity of 0 will solve your issue.

Greg

**Comment by sungeunDev** [comment]
That's it!! Thanks! 😄👍
