### ISSUE TITLE
Detect Load Completion

### ISSUE THREAD

**Issue by moderateepheezy** [gregttn/GTProgressBar#6]
How can i know when it finishes counting?

**Comment by gregttn** [comment]
I'm not sure if I understand your question. You are responsible for setting the progress displayed by the control. The control does not count by itself. Could you please clarify?

If you are asking whether you can get notified when the animation finishes then the answer is no. It will be added at some point in the future

**Comment by gregttn** [comment]
The support for detecting when bar finishes animating was added to `animateTo` method in version 0.3.0
